apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress-test-database-name" . }}
  labels:
    app: {{ template "wordpress-test.name" . }}
    chart: {{ template "wordpress-test.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wordpress-test-database-name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "wordpress-test-database-name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.database.name }}
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.version }}"
        ports:
        - containerPort: {{ .Values.database.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.database.defaults.rootpassword }}"
        - name: MYSQL_DATABASE
          value: "value: "{{ .Values.database.defaults.database }}""
        - name: MYSQL_USER
          value: "value: "{{ .Values.database.defaults.username }}""
        - name: MYSQL_PASSWORD
          value: "value: "{{ .Values.database.defaults.password }}""