# Default values for database-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

defaults:
  rootpassword: secure-password
  databasename: wordpressdb
  username: wordpress
  password: password01
