# Default values for wordpress-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80


database:
  host: test-database-database-chart
  name: wordpressdb
  username: wordpress
  password: password01